# Generated by Django 4.2.1 on 2026-03-04 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Zadajte platné telefónne číslo (napr. 09xxxxxxx alebo +4219xxxxxxxx).', regex='^(\\+421|0)[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='PSČ musí obsahovať presne 5 číslic.', regex='^\\d{2}\\s?\\d{3}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policyholder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policyholder',
                'verbose_name_plural': 'Policyholders',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=100)),
                ('insured_object', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='policyholders.policyholder')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
    ]
